In [10]:
from sklearn.preprocessing import Imputer
from sklearn import linear_model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split

In [8]:
sal_data=pd.read_csv("Salary_Data.csv")
X=sal_data.iloc[:,:-1].values
y=sal_data.iloc[:,1].values

X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
# X_train
# # # y_train
linear_regression=linear_model.LinearRegression()
linear_regression.fit(X_train,y_train)
y_pred=linear_regression.predict(x_test)
ridge=linear_model.Ridge(alpha=0.5)
ridge.fit(X,y)
ridge.predict([[20]])
# sal_data
# x_test
# plt.scatter(X_train,y_train,color="red")
# plt.plot(X_train,linear_regression.predict(X_train))

# plt.show()


array([ 214494.95938271])

In [9]:
# y_pred
ridge.predict([[10]])

array([ 120197.21127828])

In [82]:
y_test

array([  37731.,  122391.,   57081.,   63218.,  116969.,  109431.])